apiVersion: v1
kind: Service
metadata:
  labels:
    app: openssh-server
  name: openssh-server
  namespace: default
spec:
  ports:
  - port: 2222
    protocol: TCP
    targetPort: 2222
  selector:
    app: openssh-server
  sessionAffinity: None
  type: NodePort
