apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openssh-server
  name: openssh-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: openssh-server
  template:
    metadata:
      labels:
        app: openssh-server
    spec:
      containers:
      - env:
        - name: USER_NAME
          value: openssh
        - name: PUBLIC_KEY
          value: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDG+mmBIqGPVyWYozPmL9wTc3DaaBFqaJ05yfQtZdIk/pmMxp3X9FCvoZbsrTqCbLY3+Kc7YyIHUOvZ2HhT/yNcp2durpY25Wd7BY//BDY/Hp74cGXkORPWZqVha2XU/M40x/Uxj5bcRHRG8ZKirNCAdhyj8ZJHAUoiK11Vp8/htwcD7gFTvARj3VJRkCyacgF5rshst5dqbS3Apg40bMjQVfSgpnnte6zSMinDi3bn9DClxDvMl7XceQVgiPUZdQkxaieHZ0c9dGRdsq9ReIYQUKM2eESxhWtoOtkgyxggKoaK7jiyWIAIylYWVJjgHVYdKll5Z4xXxYLOPADnmD8f
            Generated-by-Nova
        image: linuxserver/openssh-server:latest
        imagePullPolicy: Always
        name: openssh-server
