apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openssh-server
  name: openssh-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: openssh-server
  template:
    metadata:
      labels:
        app: openssh-server
    spec:
      containers:
      - env:
        - name: TZ
          value: Asia/Taipei      
        - name: PGID
          value: "1000"      
        - name: USER_NAME
          value: openssh
        - name: PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              key: openssh_server.pub
              name: openssh-server-configmap
        image: linuxserver/openssh-server:latest
        imagePullPolicy: IfNotPresent
        name: openssh-server
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        volumeMounts:
        - name: config-volume
          mountPath: /config/ssh_host_keys/ssh_config
          subPath: ssh_config
          readOnly: true            
      securityContext:
          fsGroup: 1000
      volumes:
      - name: config-volume
        configMap:
          name: openssh-server-configmap
          items:
            - key: ssh_config
              path: ssh_config            