apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openssh-server
  name: openssh-server
  namespace: default
spec:
  selector:
    matchLabels:
      app: openssh-server
  template:
    metadata:
      labels:
        app: openssh-server
    spec:
      containers:
      - env:
        - name: USER_NAME
          value: openssh
        - name: PUBLIC_KEY
          valueFrom:
            configMapKeyRef:
              key: openssh_server.pub
              name: openssh-server-configmap
        image: dogkeeper886/openssh-server:latest
        imagePullPolicy: IfNotPresent
        name: openssh-server
        resources:
          limits:
            memory: 512Mi
            cpu: "1"