apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openssh-server-test
  name: openssh-server-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openssh-server-test
  template:
    metadata:
      labels:
        app: openssh-server-test
    spec:
      containers:
      - env:
        - name: PGID
          value: "1000"
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openssh-server-secret
              key: USER_PASSWORD
              optional: false
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: openssh-server-secret
              key: USER_NAME
              optional: false
        - name: PASSWORD_ACCESS
          value: 'true'
        - name: SUDO_ACCESS
          value: 'true'          
        image: linuxserver/openssh-server
        imagePullPolicy: IfNotPresent
        name: openssh-server-test
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
        volumeMounts:
        - name: config-volume
          mountPath: /config/ssh_host_keys/ssh_config
          subPath: ssh_config
          readOnly: true            
      securityContext:
          fsGroup: 1000
      volumes:
      - name: config-volume
        configMap:
          name: openssh-server-configmap
          items:
            - key: ssh_config
              path: ssh_config