apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openssh-server
  name: openssh-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openssh-server
  template:
    metadata:
      labels:
        app: openssh-server
    spec:
      containers:
      - env:
        - name: USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: openssh-server-secret
              key: USER_PASSWORD
              optional: false
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: openssh-server-secret
              key: USER_NAME
              optional: false
        - name: PASSWORD_ACCESS
          value: 'true'
        - name: SUDO_ACCESS
          value: 'true'          
        image: dogkeeper886/openssh-server
        imagePullPolicy: IfNotPresent
        name: openssh-server
        resources:
          limits:
            memory: 512Mi
            cpu: "1"